name: "SmallWindow21 Test Deploy"

on:
  push:
    branches: 
      - '!main'

jobs:
  tflint:
    name: "Run tflint on application"
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./terraform
    steps:
    - uses: actions/checkout@v2
      name: Checkout source code
    - uses: actions/cache@v2
      name: Cache plugin dir
      with:
        path: ~/.tflint.d/plugins
        key: ${{ matrix.os }}-tflint-${{ hashFiles('.tflint.hcl') }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

    - name: Terraform Format
      id: fmt
      run: terraform fmt -recursive -check

    - name: Terraform Init
      id: init
      run: terraform init    
    - name: Setup TFLint
      uses: terraform-linters/setup-tflint@v1
      with:
        tflint_version: v0.30.0

    - name: Show version
      run: tflint --version

    - name: Init TFLint
      run: tflint --init

    - name: Run TFLint root module
      run: tflint --module -f compact 
    - name: Run TFLint security module
      run: tflint --module security -f compact 
    - name: Run TFLint networking module
      run: tflint --module networking -f compact 
    - name: Run TFLint database module
      run: tflint --module database -f compact 
    - name: Run TFLint storage module
      run: tflint --module storage -f compact 
    - name: Run TFLint compute module
      run: tflint --module compute -f compact 

  build-application:
    name: "Build Application"
    runs-on: ubuntu-latest
    needs: tflint
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - run: mvn -B clean install --file app/pom.xml
      - run: mkdir appTests && cp app/target/smallwindow-21-0.0.1-SNAPSHOT.jar appTests
      - uses: actions/upload-artifact@v2
        with:
          name: TestPackage
          path: appTests 
